Repository MechaLions/Sonsori-FE, pull requests merged in 2024-09, with the labels that each got.

#11 style: 번역 페이지 개발
  package-lock.json
  package.json
  src/assets/TextBoxEndQuoteIcon.png
  src/assets/TextBoxStartQuoteIcon.png
  src/assets/translateBackground.png
  src/components/Icons/EndQuoteIcon.tsx
  src/components/Icons/StartQuoteIcon.tsx
  src/pages/translate/_components/ButtonSection.tsx
  src/pages/translate/_components/TextBoxSection.tsx
  src/pages/translate/_components/VideoSection.tsx
  src/pages/translate/index.tsx
  tailwind.config.js
  ui/globals.css
Labels: 🎨 style

#12 style: 발음 교정 레이아웃 구현
  components.json
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/assets/PronunciationBackground.png
  src/assets/micImage.png
  src/components/Icons/MicIcon.tsx
  src/components/ProgressBar.tsx
  src/pages/_app.tsx
  src/pages/pronunciation/_components/Activity.tsx
  src/pages/pronunciation/_components/AnswerActivity.tsx
  src/pages/pronunciation/_components/AnswerCompareSection.tsx
  src/pages/pronunciation/_components/AnswerSection.tsx
  src/pages/pronunciation/_components/BackCardView.tsx
  src/pages/pronunciation/_components/CategoryItem.tsx
  src/pages/pronunciation/_components/CategorySection.tsx
  src/pages/pronunciation/_components/ExplainSection.tsx
  src/pages/pronunciation/_components/FrontCardView.tsx
  src/pages/pronunciation/_components/MainActivity.tsx
  src/pages/pronunciation/_components/MicDialog.tsx
  src/pages/pronunciation/_components/PromptSection.tsx
  src/pages/pronunciation/_components/QuizActivity.tsx
  src/pages/pronunciation/index.tsx
  src/utils/pronunciationflow.ts
  src/utils/usePronunciationFlow.ts
  tailwind.config.js
  ui/globals.css
  ui/src/components/ui/alert-dialog.tsx
  ui/src/components/ui/button.tsx
  ui/src/components/ui/carousel.tsx
  ui/src/components/ui/dialog.tsx
Labels: 🎨 style

#16 style: 로고 수정
  index.html
  src/assets/LogoImage.png
  src/assets/RoundLogo.svg
  src/components/Icons/Logo.tsx
  src/pages/home/_components/MainSection.tsx
  src/pages/home/_components/TranslateSection.tsx
  src/pages/translate/index.tsx
Labels: 🎨 style

#17 style: 쉐도잉 페이지 레이아웃 구현
  src/assets/PauseIcon.png
  src/assets/PlayIcon.png
  src/assets/ReplayIcon.png
  src/assets/ShadowingBackground.png
  src/assets/UndoIcon.png
  src/components/Icons/PauseIcon.tsx
  src/components/Icons/PlayIcon.tsx
  src/components/Icons/ReplayIcon.tsx
  src/components/Icons/UndoIcon.tsx
  src/pages/shadowing/_components/Activity.tsx
  src/pages/shadowing/_components/AnswerActivity.tsx
  src/pages/shadowing/_components/AnswerCompareSection.tsx
  src/pages/shadowing/_components/AnswerSection.tsx
  src/pages/shadowing/_components/BackCardView.tsx
  src/pages/shadowing/_components/CategoryItem.tsx
  src/pages/shadowing/_components/CategorySection.tsx
  src/pages/shadowing/_components/ExplainSection.tsx
  src/pages/shadowing/_components/FrontCardView.tsx
  src/pages/shadowing/_components/MainActivity.tsx
  src/pages/shadowing/_components/PromptSection.tsx
  src/pages/shadowing/_components/QuestionSection.tsx
  src/pages/shadowing/_components/QuizActivity.tsx
  src/pages/shadowing/_components/UserAnswerSection.tsx
  src/pages/shadowing/index.tsx
  src/utils/shadowing/shadowingflow.ts
  src/utils/shadowing/useShadowingFlow.ts
  tailwind.config.js
  ui/globals.css
Labels: 🎨 style

#22 fix: 쉐도잉 페이지 정답 비교 프롬프트 수정
  src/pages/shadowing/_components/AnswerCompareSection.tsx
Labels: ⚒️ fix

#23 refactor: 공통 컴포넌트 리팩토링
  src/components/Activity.tsx
  src/components/BackCardView.tsx
  src/components/FrontCardView.tsx
  src/components/Icons/Logo.tsx
  src/pages/pronunciation/_components/Activity.tsx
  src/pages/pronunciation/_components/AnswerActivity.tsx
  src/pages/pronunciation/_components/AnswerSection.tsx
  src/pages/pronunciation/_components/CategoryItem.tsx
  src/pages/pronunciation/_components/PromptSection.tsx
  src/pages/pronunciation/_components/QuizActivity.tsx
  src/pages/quiz/_components/Activity.tsx
  src/pages/quiz/_components/ExplainSection.tsx
  src/pages/quiz/_components/MainActivity.tsx
  src/pages/quiz/_components/PromptSection.tsx
  src/pages/quiz/_components/QuizActivity.tsx
  src/pages/quiz/_components/ResultActivity.tsx
  src/pages/shadowing/_components/Activity.tsx
  src/pages/shadowing/_components/AnswerActivity.tsx
  src/pages/shadowing/_components/AnswerSection.tsx
  src/pages/shadowing/_components/BackCardView.tsx
  src/pages/shadowing/_components/CategoryItem.tsx
  src/pages/shadowing/_components/FrontCardView.tsx
  src/pages/shadowing/_components/PromptSection.tsx
  src/pages/shadowing/_components/QuizActivity.tsx
  src/pages/user-auth/index.tsx
Labels: ⚒️ fix, ⚡️ refactor

#25 feat: 로그인&회원가입 api 연결
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/api/auth.ts
  src/api/instance.ts
  src/components/AuthRequiredModal.tsx
  src/components/Nav.tsx
  src/hooks/mutations/useMutationCheckID.ts
  src/hooks/mutations/useMutationLogin.ts
  src/hooks/mutations/useMutationSignUp.ts
  src/hooks/useControlRedirect.ts
  src/hooks/useLogin.ts
  src/hooks/useSignUp.ts
  src/pages/_app.tsx
  src/pages/user-auth/_components/ErrorMentBox.tsx
  src/pages/user-auth/_components/InputItem.tsx
  src/pages/user-auth/_components/LoginSection.tsx
  src/pages/user-auth/_components/SignupSection.tsx
  src/types/authType.ts
  src/utils/handleID.ts
  ui/src/components/ui/dialog.tsx
  ui/src/components/ui/toast.tsx
  ui/src/components/ui/toaster.tsx
  ui/src/hooks/use-toast.ts
Labels: ✨ feat

#30 feat: 수어번역 api 연결
  package-lock.json
  package.json
  src/hooks/useVideoStream.ts
  src/pages/translate/_components/ButtonSection.tsx
  src/pages/translate/_components/TextBoxSection.tsx
  src/pages/translate/_components/VideoSection.tsx
  src/pages/translate/index.tsx
Labels: ✨ feat

#33 feat: 쉐도잉 api 연결 일부 완료
  src/pages/shadowing/_components/AnswerActivity.tsx
  src/pages/shadowing/_components/AnswerCompareSection.tsx
  src/pages/shadowing/_components/AnswerSection.tsx
  src/pages/shadowing/_components/CategoryItem.tsx
  src/pages/shadowing/_components/CategorySection.tsx
  src/pages/shadowing/_components/PromptSection.tsx
  src/pages/shadowing/_components/QuestionSection.tsx
  src/pages/shadowing/_components/QuizActivity.tsx
  src/pages/shadowing/_components/UserAnswerSection.tsx
Labels: ✨ feat

#34 feat: 발음 교정 api 연결
  src/api/auth.ts
  src/api/pronunciation.ts
  src/hooks/mutations/useMutationPronunSaveAccuracy.ts
  src/pages/pronunciation/_components/AnswerCompareSection.tsx
  src/pages/pronunciation/_components/AnswerSection.tsx
  src/pages/pronunciation/_components/MicDialog.tsx
  src/pages/pronunciation/_components/QuizActivity.tsx
Labels: ✨ feat
